### ISSUE TITLE
test for date parts

### ISSUE THREAD

**Issue by libora** [citation-style-language/csl-evolution#2] opened 2017-05-04 18:39 UTC
For ISO 690 is important to be able to test if the only year is filled in the date field.
https://forums.zotero.org/discussion/29298/the-conditioned-date-display

**Comment by bwiernik** [comment] 2020-05-25 20:28
@bdarcus Can you give me triage access to this repo too so I can close some duplicate issues?

**Comment by bdarcus** [comment] 2020-05-25 20:40
Done. Also on documentation.

>

**Comment by bwiernik** [comment] 2020-05-25 20:43
Duplicate of https://github.com/citation-style-language/csl-evolution/issues/8 and https://github.com/citation-style-language/schema/issues/32

**Closed as completed by bwiernik** 2020-05-25 20:43 UTC
